name: Contrôle Raspberry Pi

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH au Raspberry Pi
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 192.168.1.77
          username: pi
          key: ${{ secrets.RASPBERRY_SSH_KEY }}
          script: |
            cd /home/pi/Bras-robot
            git pull origin main
            python3 /home/pi/Bras-robot/server_ws.py
